// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, public_member_api_docs
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDREqa6TwaHbjHA7XYCsZbWpbgivae1KkU',
    appId: '1:377759081959:web:74ad0c3c8293266cab0942',
    messagingSenderId: '377759081959',
    projectId: 'cvault-2f761',
    authDomain: 'cvault-2f761.firebaseapp.com',
    storageBucket: 'cvault-2f761.appspot.com',
    measurementId: 'G-L0Y8C9ENS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpuwRGBnUdQj8iY1G0l9h3OhCEueSzPNY',
    appId: '1:377759081959:android:0deee39f1332859eab0942',
    messagingSenderId: '377759081959',
    projectId: 'cvault-2f761',
    storageBucket: 'cvault-2f761.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA1TjReS3sdQCqYLzuS2_OPUGVwxMm47Y',
    appId: '1:377759081959:ios:b7d9d456a8f4cd2eab0942',
    messagingSenderId: '377759081959',
    projectId: 'cvault-2f761',
    storageBucket: 'cvault-2f761.appspot.com',
    androidClientId:
        '377759081959-14652pmvi14t9lg8s0khoak7825jni49.apps.googleusercontent.com',
    iosClientId:
        '377759081959-439o15mmdo9l1ufodim1nvfgp3astomv.apps.googleusercontent.com',
    iosBundleId: 'com.kodekrewcvault.com',
  );
}
